# Copied from https://github.com/awslabs/aws-lambda-rust-runtime/blob/f69280e9b92e9a7acc92cfa04a860d9b2b83b5c0/.github/actions/rust-build/action.yml
#
name: "Rust builds"
description: "Builds and tests rust code"
inputs:
  toolchain:
    required: true
    description: "the Rust toolchain to use"
  flags:
    required: true
    description: "the flags to pass"

runs:
  using: "composite"
  steps:
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ inputs.toolchain }}
    - uses: Swatinem/rust-cache@v2
    - name: Build
      shell: bash
      run: |
          if [ "${{ inputs.toolchain }}" != stable ]; then
              rm -fv Cargo.lock
          fi
          cargo build --verbose ${{ inputs.flags }}
    - name: Run tests
      shell: bash
      run: |
          cargo test --verbose ${{ inputs.flags }}
          if [ "${{ inputs.toolchain }}" == nightly -a "${{ inputs.flags }}" == "--all-features" ]; then
              # docs use unstable features, run them on nightly
              RUSTDOCFLAGS="-D warnings --cfg docsrs" cargo doc --verbose ${{ inputs.flags }}
          fi
