//! Example of the types generated by [`metrics`].
//!
//! **These types exist for documentation only and must not be used by applications.**
//! A normal macro invocation generates the same shapes in the caller's module.

use crate::{Counter, timers::Timer, unit::Millisecond, unit_of_work::metrics};

/// Representative input passed to the `metrics` macro.
#[metrics(__docs, rename_all = "PascalCase")]
pub struct RequestMetrics {
    /// Number of requests handled.
    pub request_count: Counter,
    /// Time spent handling the request.
    #[metrics(unit = Millisecond)]
    pub latency: Timer,
}
