// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

//! Structural extraction of dimension `(class, instance)` pairs from an aggregate entry.
//!
//! Unlike a runtime "probe" that writes the whole entry through a no-op
//! [`EntryWriter`](metrique_writer::EntryWriter) just to observe which
//! dimensions it announces, this module reads the dimensional fields directly.
//!
//! The `#[aggregate]` macro knows, at compile time, exactly which fields carry
//! [`WithDimensions`] (and which `Flatten` fields nest further aggregate structs).
//! It uses that structural knowledge to generate a [`CollectDimensions`] impl per
//! aggregate struct that visits only the fields that can contribute dimensions —
//! recursing into flattened children — instead of traversing every value.

use metrique_writer::value::WithDimensions;
use smallvec::SmallVec;
use std::borrow::Cow;

type CowStr = Cow<'static, str>;

/// The inline capacity used for the collected dimension set.
///
/// Most entries carry only a handful of dimensions; this keeps the common case
/// allocation-free.
pub type DimensionSet = SmallVec<[(CowStr, CowStr); 4]>;

/// Structurally collect the dimension `(class, instance)` pairs an aggregate
/// entry contributes to its merge key.
///
/// The `#[aggregate]` macro generates an implementation for every aggregate
/// struct, visiting each [`WithDimensions`] field directly and recursing into
/// `Flatten` fields. [`WithDimensions`] itself implements this trait by pushing
/// its own dimensions.
///
/// This is the compile-time-directed replacement for the old runtime write
/// probe: it touches only the fields that can carry dimensions, and never runs
/// the value-writing machinery.
pub trait CollectDimensions {
    /// Append every `(class, instance)` pair this value contributes to `out`.
    fn collect_dimensions(&self, out: &mut DimensionSet);
}

impl<V, const N: usize> CollectDimensions for WithDimensions<V, N> {
    fn collect_dimensions(&self, out: &mut DimensionSet) {
        out.extend(self.dimensions().iter().cloned());
    }
}

/// Extract all `(class, instance)` dimension pairs from an aggregate entry,
/// canonicalized (sorted + dedup'd) so that the resulting set is order-independent.
///
/// This is what the macro-generated `Key::from_source` calls. The input's
/// [`CollectDimensions`] impl is generated by `#[aggregate]`.
pub fn extract_dimensions<T: CollectDimensions + ?Sized>(entry: &T) -> DimensionSet {
    let mut dimensions = SmallVec::new();
    entry.collect_dimensions(&mut dimensions);
    dimensions.sort();
    dimensions.dedup();
    dimensions
}

#[cfg(test)]
mod tests {
    use super::*;
    use metrique_writer::MetricValue;
    use metrique_writer::value::{WithDimension, WithDimensions};
    use std::time::Duration;

    #[test]
    fn empty_entry() {
        struct Empty;
        impl CollectDimensions for Empty {
            fn collect_dimensions(&self, _out: &mut DimensionSet) {}
        }
        let dims = extract_dimensions(&Empty);
        assert!(dims.is_empty());
    }

    #[test]
    fn single_dimension() {
        struct SingleDimEntry {
            value: WithDimension<u64>,
        }
        impl CollectDimensions for SingleDimEntry {
            fn collect_dimensions(&self, out: &mut DimensionSet) {
                self.value.collect_dimensions(out);
            }
        }
        let entry = SingleDimEntry {
            value: 42u64.with_dimension("Event", "GET"),
        };
        let dims = extract_dimensions(&entry);
        assert_eq!(
            dims.as_slice(),
            &[(Cow::Borrowed("Event"), Cow::Borrowed("GET"))]
        );
    }

    #[test]
    fn multiple_dimensions_different_classes() {
        struct Multi {
            a: WithDimension<u64>,
            b: WithDimension<u64>,
        }
        impl CollectDimensions for Multi {
            fn collect_dimensions(&self, out: &mut DimensionSet) {
                self.a.collect_dimensions(out);
                self.b.collect_dimensions(out);
            }
        }
        let entry = Multi {
            a: 1u64.with_dimension("Event", "GET"),
            b: 2u64.with_dimension("Region", "us-east-1"),
        };
        let dims = extract_dimensions(&entry);
        assert_eq!(dims.len(), 2);
        assert!(dims.contains(&(Cow::Borrowed("Event"), Cow::Borrowed("GET"))));
        assert!(dims.contains(&(Cow::Borrowed("Region"), Cow::Borrowed("us-east-1"))));
    }

    #[test]
    fn dedup_identical_pairs() {
        struct Dup {
            a: WithDimension<u64>,
            b: WithDimension<u64>,
        }
        impl CollectDimensions for Dup {
            fn collect_dimensions(&self, out: &mut DimensionSet) {
                self.a.collect_dimensions(out);
                self.b.collect_dimensions(out);
            }
        }
        let entry = Dup {
            a: 1u64.with_dimension("Event", "GET"),
            b: 2u64.with_dimension("Event", "GET"),
        };
        let dims = extract_dimensions(&entry);
        assert_eq!(dims.len(), 1);
    }

    #[test]
    fn same_class_different_instance() {
        struct Multi {
            a: WithDimension<u64>,
            b: WithDimension<u64>,
        }
        impl CollectDimensions for Multi {
            fn collect_dimensions(&self, out: &mut DimensionSet) {
                self.a.collect_dimensions(out);
                self.b.collect_dimensions(out);
            }
        }
        let entry = Multi {
            a: 1u64.with_dimension("Event", "GET"),
            b: 2u64.with_dimension("Event", "POST"),
        };
        let dims = extract_dimensions(&entry);
        assert_eq!(dims.len(), 2);
    }

    #[test]
    fn sorting_canonicalization() {
        struct Multi {
            a: WithDimension<u64>,
            b: WithDimension<u64>,
        }
        impl CollectDimensions for Multi {
            fn collect_dimensions(&self, out: &mut DimensionSet) {
                self.a.collect_dimensions(out);
                self.b.collect_dimensions(out);
            }
        }
        let entry = Multi {
            a: 1u64.with_dimension("Zebra", "z"),
            b: 2u64.with_dimension("Alpha", "a"),
        };
        let dims = extract_dimensions(&entry);
        assert_eq!(dims[0], (Cow::Borrowed("Alpha"), Cow::Borrowed("a")));
        assert_eq!(dims[1], (Cow::Borrowed("Zebra"), Cow::Borrowed("z")));
    }

    #[test]
    fn runtime_set_dimensions_via_add_dimension() {
        let mut val: WithDimensions<u64, 2> = WithDimensions::from(10u64);
        val.add_dimension("Year", "2025");
        val.add_dimension("Season", "Spring");

        struct DynEntry {
            value: WithDimensions<u64, 2>,
        }
        impl CollectDimensions for DynEntry {
            fn collect_dimensions(&self, out: &mut DimensionSet) {
                self.value.collect_dimensions(out);
            }
        }
        let entry = DynEntry { value: val };
        let dims = extract_dimensions(&entry);
        assert_eq!(dims.len(), 2);
        assert!(dims.contains(&(Cow::Borrowed("Season"), Cow::Borrowed("Spring"))));
        assert!(dims.contains(&(Cow::Borrowed("Year"), Cow::Borrowed("2025"))));
    }

    #[test]
    fn nested_via_flatten() {
        struct Inner {
            value: WithDimension<Duration>,
        }
        impl CollectDimensions for Inner {
            fn collect_dimensions(&self, out: &mut DimensionSet) {
                self.value.collect_dimensions(out);
            }
        }
        struct Outer {
            inner: Inner,
        }
        impl CollectDimensions for Outer {
            fn collect_dimensions(&self, out: &mut DimensionSet) {
                // Flatten fields recurse into the child's own impl.
                self.inner.collect_dimensions(out);
            }
        }
        let entry = Outer {
            inner: Inner {
                value: Duration::from_millis(10).with_dimension("Op", "Read"),
            },
        };
        let dims = extract_dimensions(&entry);
        assert_eq!(dims.len(), 1);
        assert_eq!(dims[0], (Cow::Borrowed("Op"), Cow::Borrowed("Read")));
    }
}
