// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

//! Collects metrics from decoupled producers and flattens them into one parent entry.
//!
//! A pool lets code that cannot name the parent metric type—such as middleware,
//! SDK interceptors, or libraries—contribute child metrics. To include a pool in
//! an entry, annotate its containing field with `#[metrics(flatten)]`; that
//! annotation tells `#[metrics]` to emit the pool's fields in the parent entry.
//! Producers append child metrics through a [`MetricsPoolHandle`].
//!
//! ```no_run
//! use metrique::unit_of_work::metrics;
//! use metrique_util::MetricsPool;
//!
//! #[metrics(rename_all = "PascalCase")]
//! struct RequestMetrics {
//!     operation: &'static str,
//!     #[metrics(flatten)]
//!     pool: MetricsPool,
//! }
//!
//! #[metrics(rename_all = "PascalCase")]
//! struct AttemptMetrics {
//!     retry_count: u32,
//! }
//!
//! # fn example(sink: impl metrique::writer::EntrySink<metrique::RootEntry<RequestMetricsEntry>> + Send + Sync + 'static) {
//! let request = RequestMetrics { operation: "PutObject", pool: MetricsPool::new() }
//!     .append_on_drop(sink);
//!
//! // A producer can keep this handle without depending on `RequestMetrics`.
//! request.pool.handle().with_prefix(["sdk", "s3"])
//!     .append(AttemptMetrics { retry_count: 2 });
//!
//! // Dropping `request` emits `Operation` and `SdkS3RetryCount`.
//! # }
//! ```
//!
//! # Scoped access
//!
//! Pass a handle explicitly, or use [`with_metrics_pool`] to make one available
//! through [`MetricsPool::current`] while a future is polled. This scope is tied
//! to future polls, not to a thread or logical request:
//!
//! - Spawned tasks start without the scope. Wrap their future with
//!   [`propagate_current`] at the spawn site, or capture a handle and move it into
//!   detached work explicitly.
//! - `spawn_blocking` closures and threads cannot use a future wrapper; capture a
//!   handle before spawning and move it into the closure.
//! - Blocking inside a scoped poll can expose the pool to unrelated work running
//!   on that thread, corrupting attribution. Pass handles explicitly instead.
//!
//! `MetricsPool::current` returns `None` both when no pool is installed and when
//! work was detached from a scope. Producers should use a standalone sink in
//! that case rather than discard the metric.
//!
//! # Naming and prefixes
//!
//! [`MetricsPoolHandle::with_prefix`] follows the parent name style: the same
//! prefix becomes `SdkS3RetryCount` in `PascalCase` and `sdk_s3_retry_count` in
//! `snake_case`. Use [`MetricsPoolHandle::with_exact_prefix`] for literal
//! prefixes such as `sdk.request.`.
//!
//! # Parent lifetime
//!
//! Closing the parent closes the pool and drains the children collected so far.
//! Appends after that point are discarded with a rate-limited warning, so child
//! producers and append-on-drop guards must finish before the parent guard drops.
//!
//! # Capacity and overflow
//!
//! A pool retains at most 128 child entries by default. Each append consumes one
//! slot regardless of how many fields the child writes. When the pool is full,
//! appending never waits for free capacity: the oldest child is evicted and a
//! rate-limited warning is emitted. Use [`MetricsPool::builder`] to configure
//! the capacity and [`MetricsPool::overflow_count`] or
//! [`MetricsPoolHandle::overflow_count`] to observe evictions.
//!
//! # Entry metadata and sampling
//!
//! Pooled children contribute fields but do not replace parent entry metadata by
//! default: child timestamps and [`EntryConfig`] calls are suppressed. A producer
//! can deliberately forward them through
//! [`MetricsPoolHandle::forward_entry_metadata`], but a second timestamp or
//! incompatible configuration can invalidate the parent record. Child sample
//! groups are always ignored and cannot change the parent's sampling policy.
//!
//! # Collision policy
//!
//! Collisions are compared using fully inflected field names among children in
//! the same pool. If two children collide, the later child wins and the earlier
//! child is dropped in full, preventing fields from separate attempts from being
//! combined into a record that never existed.
//!
//! Collision handling writes surviving children twice: once to scan their field
//! names and once to emit them. A closed child must emit the same set of field
//! names on every write. Values and field order may change, but interior
//! mutability must not change which names are present. Entries generated by
//! `#[metrics]` satisfy this unless they flatten a custom entry that violates the
//! requirement. Debug builds assert when a child changes its field names between
//! passes.
//!
//! The pool cannot detect collisions with ordinary parent fields or other
//! flattened components. Give producers distinct prefixes from one another and
//! from the parent entry. Collision detection also replays child entries, so use
//! a pool at integration boundaries where the parent cannot name child types;
//! prefer statically typed flattened fields otherwise.

use core::future::Future;
use core::pin::Pin;
use core::task::{Context, Poll};
use std::borrow::Cow;
use std::cell::RefCell;
use std::collections::{BTreeSet, HashMap, HashSet, VecDeque};
use std::fmt::Debug;
use std::sync::atomic::{AtomicU64, Ordering};
use std::sync::{Arc, Mutex, OnceLock};
use std::time::{Duration, SystemTime};

use metrique::writer::rate_limit::rate_limited;
use metrique::writer::sink::FlushWait;
use metrique::writer::{
    BoxEntry, Entry, EntryConfig, EntrySink, EntryWriter, Value, core::Descriptors,
};
use metrique::{
    AppendAndCloseOnDrop, CloseValue, Identity, InflectableEntry, KebabCase, NameStyle, PascalCase,
    RootEntry, SnakeCase, append_and_close,
    concat::{EmptyConstStr, const_str_value},
};
use metrique_core::case_convert::CaseStyle;
use metrique_core::{CloseEntry, Styles};

use crate::MetricNameStyle;
use crate::dynamic_inflection::DynamicInflectionEntry;

/// Return the runtime equivalent of a compile-time [`NameStyle`].
fn dynamic_name_style<NS: NameStyle>() -> MetricNameStyle {
    match NS::DESCRIPTOR_STYLE_INDEX {
        index if index == Styles::PASCAL.index => MetricNameStyle::PascalCase,
        index if index == Styles::SNAKE.index => MetricNameStyle::SnakeCase,
        index if index == Styles::KEBAB.index => MetricNameStyle::KebabCase,
        _ => MetricNameStyle::Identity,
    }
}

const DEFAULT_METRICS_POOL_CAPACITY: usize = 128;

thread_local! {
    // Poll scopes can nest and futures can interleave on one thread, so this is
    // a stack. The last installed handle is current and dropping its guard
    // restores the enclosing scope.
    static CURRENT_POOL: RefCell<Vec<MetricsPoolHandle>> = const { RefCell::new(Vec::new()) };
}

fn intern_prefix(prefix: String) -> &'static str {
    static INTERNED: OnceLock<Mutex<HashMap<String, &'static str>>> = OnceLock::new();
    let interned = INTERNED.get_or_init(|| Mutex::new(HashMap::new()));
    let mut interned = interned.lock().unwrap();

    if let Some(existing) = interned.get(prefix.as_str()) {
        return existing;
    }

    let leaked = Box::leak(prefix.clone().into_boxed_str());
    interned.insert(prefix, leaked);
    leaked
}

#[derive(Clone, Copy, Debug)]
enum PrefixPart {
    Segment(&'static str),
    Exact(&'static str),
}

struct PrefixCache {
    identity: OnceLock<&'static str>,
    pascal: OnceLock<&'static str>,
    snake: OnceLock<&'static str>,
    kebab: OnceLock<&'static str>,
}

impl PrefixCache {
    fn new() -> Self {
        Self {
            identity: OnceLock::new(),
            pascal: OnceLock::new(),
            snake: OnceLock::new(),
            kebab: OnceLock::new(),
        }
    }

    fn for_style(&self, style: MetricNameStyle) -> &OnceLock<&'static str> {
        match style {
            MetricNameStyle::PascalCase => &self.pascal,
            MetricNameStyle::SnakeCase => &self.snake,
            MetricNameStyle::KebabCase => &self.kebab,
            _ => &self.identity,
        }
    }
}

struct PrefixData {
    parts: Box<[PrefixPart]>,
    cache: PrefixCache,
}

#[derive(Clone)]
struct PrefixSet(Arc<PrefixData>);

impl PrefixSet {
    fn empty() -> Self {
        Self(Arc::new(PrefixData {
            parts: Box::new([]),
            cache: PrefixCache::new(),
        }))
    }

    fn with_segments<I>(&self, segments: I) -> Self
    where
        I: IntoIterator<Item = &'static str>,
    {
        self.with_parts(
            segments
                .into_iter()
                .filter(|segment| !segment.is_empty())
                .map(PrefixPart::Segment),
        )
    }

    fn with_exact_prefix(&self, prefix: &'static str) -> Self {
        self.with_parts((!prefix.is_empty()).then_some(PrefixPart::Exact(prefix)))
    }

    fn with_parts(&self, parts: impl IntoIterator<Item = PrefixPart>) -> Self {
        let mut parts = parts.into_iter().peekable();
        if parts.peek().is_none() {
            return self.clone();
        }

        let mut combined = Vec::with_capacity(self.0.parts.len() + parts.size_hint().0);
        combined.extend_from_slice(&self.0.parts);
        combined.extend(parts);
        Self(Arc::new(PrefixData {
            parts: combined.into_boxed_slice(),
            cache: PrefixCache::new(),
        }))
    }

    fn for_style(&self, style: MetricNameStyle) -> &'static str {
        self.0
            .cache
            .for_style(style)
            .get_or_init(|| self.render(style))
    }

    fn render(&self, style: MetricNameStyle) -> &'static str {
        match self.0.parts.as_ref() {
            [] => return "",
            [PrefixPart::Exact(exact)] => return exact,
            _ => {}
        }

        let mut prefix = String::new();
        for part in &self.0.parts {
            match *part {
                PrefixPart::Segment(segment) => {
                    prefix.push_str(&prefix_segment(style, segment));
                }
                PrefixPart::Exact(exact) => prefix.push_str(exact),
            }
        }
        if prefix.is_empty() {
            ""
        } else {
            intern_prefix(prefix)
        }
    }
}

fn prefix_segment(style: MetricNameStyle, segment: &str) -> String {
    let case_style = match style {
        MetricNameStyle::PascalCase => CaseStyle::Pascal,
        MetricNameStyle::SnakeCase => CaseStyle::Snake,
        MetricNameStyle::KebabCase => CaseStyle::Kebab,
        _ => CaseStyle::Preserve,
    };
    // `apply_prefix` appends the trailing `_`/`-` for delimited styles and
    // leaves delimiter-free styles alone.
    let mut prefix = case_style.apply_prefix(segment);
    // A preserved pool segment is a path component, rather than a literal
    // prefix, so it still needs a separator (`with_exact_prefix` is literal).
    if matches!(style, MetricNameStyle::Identity)
        && !prefix.ends_with('_')
        && !prefix.ends_with('-')
    {
        prefix.push('_');
    }
    prefix
}

struct MetricsPoolInner {
    entries: Mutex<Option<VecDeque<BufferedEntry>>>,
    capacity: usize,
    overflow_count: AtomicU64,
}

impl MetricsPoolInner {
    fn new(capacity: usize) -> Self {
        Self {
            entries: Mutex::new(Some(VecDeque::new())),
            capacity,
            overflow_count: AtomicU64::new(0),
        }
    }

    fn push(&self, entry: BufferedEntry) {
        enum PushOutcome {
            Appended,
            AppendedWithEviction {
                _oldest: BufferedEntry,
                overflow_count: u64,
            },
            Closed {
                _rejected: BufferedEntry,
            },
        }

        let outcome = {
            let mut state = self.entries.lock().unwrap();
            match state.as_mut() {
                Some(entries) => {
                    let oldest = if entries.len() >= self.capacity {
                        entries.pop_front()
                    } else {
                        None
                    };
                    entries.push_back(entry);
                    match oldest {
                        Some(oldest) => PushOutcome::AppendedWithEviction {
                            _oldest: oldest,
                            overflow_count: self.overflow_count.fetch_add(1, Ordering::Relaxed) + 1,
                        },
                        None => PushOutcome::Appended,
                    }
                }
                None => PushOutcome::Closed { _rejected: entry },
            }
        };

        // Drop discarded children after unlocking: a child's destructor may
        // append to this pool and would deadlock trying to reacquire the mutex.
        match outcome {
            PushOutcome::Appended => {}
            PushOutcome::AppendedWithEviction { overflow_count, .. } => {
                rate_limited!(
                    Duration::from_secs(1),
                    tracing::warn!(
                        capacity = self.capacity,
                        overflow_count,
                        "MetricsPool is full; dropped the oldest child entry"
                    )
                );
            }
            PushOutcome::Closed { .. } => {
                rate_limited!(
                    Duration::from_secs(60),
                    tracing::warn!(
                        "MetricsPool dropped an entry appended after close; parent closed before producers finished"
                    )
                );
            }
        }
    }

    fn take(&self) -> VecDeque<BufferedEntry> {
        self.entries.lock().unwrap().take().unwrap_or_default()
    }

    fn overflow_count(&self) -> u64 {
        self.overflow_count.load(Ordering::Relaxed)
    }
}

/// Configures a [`MetricsPool`].
#[derive(Clone, Copy, Debug)]
pub struct MetricsPoolBuilder {
    capacity: usize,
}

impl MetricsPoolBuilder {
    /// Create a builder with the default capacity of 128 child entries.
    pub fn new() -> Self {
        Self::default()
    }

    /// Set the maximum number of child entries retained by the pool.
    ///
    /// Each append consumes one slot regardless of how many fields that child
    /// writes. Once the pool is full, appending a child evicts the oldest child.
    ///
    /// # Panics
    ///
    /// Panics if `capacity` is zero.
    pub fn capacity(mut self, capacity: usize) -> Self {
        assert!(
            capacity > 0,
            "MetricsPool capacity must be greater than zero"
        );
        self.capacity = capacity;
        self
    }

    /// Build a metrics pool with this configuration.
    pub fn build(self) -> MetricsPool {
        MetricsPool {
            inner: Arc::new(MetricsPoolInner::new(self.capacity)),
        }
    }
}

impl Default for MetricsPoolBuilder {
    fn default() -> Self {
        Self {
            capacity: DEFAULT_METRICS_POOL_CAPACITY,
        }
    }
}

/// The request-owned collection point for pooled child metrics.
///
/// Store one pool in the parent metric entry under `#[metrics(flatten)]`, then
/// distribute [`MetricsPoolHandle`]s to producers. A default pool retains the
/// latest 128 child entries. Closing the parent consumes the pool and emits the
/// children collected before that close; later appends are discarded.
///
/// See the [`metrics_pool`](crate::metrics_pool) module guide for scoped access,
/// naming, metadata, lifetime, and collision policies.
pub struct MetricsPool {
    inner: Arc<MetricsPoolInner>,
}

impl MetricsPool {
    /// The maximum number of child entries retained by a default pool.
    pub const DEFAULT_CAPACITY: usize = DEFAULT_METRICS_POOL_CAPACITY;

    /// Create an empty metrics pool with capacity for 128 child entries.
    pub fn new() -> Self {
        Self::builder().build()
    }

    /// Create a builder for configuring a metrics pool.
    pub fn builder() -> MetricsPoolBuilder {
        MetricsPoolBuilder::new()
    }

    /// Return the maximum number of child entries this pool retains.
    pub fn capacity(&self) -> usize {
        self.inner.capacity
    }

    /// Return the number of oldest child entries evicted due to capacity.
    pub fn overflow_count(&self) -> u64 {
        self.inner.overflow_count()
    }

    /// Return a cloneable handle to this pool.
    pub fn handle(&self) -> MetricsPoolHandle {
        MetricsPoolHandle {
            inner: Arc::clone(&self.inner),
            prefixes: PrefixSet::empty(),
            forward_entry_metadata: false,
        }
    }

    /// Install this pool while `future` is being polled.
    pub fn scope<F>(&self, future: F) -> MetricsPoolScope<F> {
        self.handle().scope(future)
    }

    /// Return the pool installed for the current future poll, if any.
    ///
    /// The scope does not cross a task spawn, blocking-task spawn, or thread
    /// boundary. `None` therefore means either that no pool is installed or that
    /// this work was detached from one. Pass a handle into detached work, and use
    /// a standalone sink when no pool is available.
    pub fn current() -> Option<MetricsPoolHandle> {
        CURRENT_POOL.with(|current| current.borrow().last().cloned())
    }
}

impl Default for MetricsPool {
    fn default() -> Self {
        Self::new()
    }
}

impl Debug for MetricsPool {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let entry_count = self
            .inner
            .entries
            .lock()
            .unwrap()
            .as_ref()
            .map_or(0, VecDeque::len);

        f.debug_struct("MetricsPool")
            .field("entry_count", &entry_count)
            .field("capacity", &self.inner.capacity)
            .field("overflow_count", &self.inner.overflow_count())
            .finish()
    }
}

impl CloseValue for MetricsPool {
    type Closed = MetricsPoolEntry;

    fn close(self) -> Self::Closed {
        MetricsPoolEntry {
            entries: self.inner.take(),
        }
    }
}

/// Cloneable producer handle for a [`MetricsPool`].
#[derive(Clone)]
pub struct MetricsPoolHandle {
    inner: Arc<MetricsPoolInner>,
    prefixes: PrefixSet,
    forward_entry_metadata: bool,
}

impl Debug for MetricsPoolHandle {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("MetricsPoolHandle")
            .field(
                "identity_prefix",
                &self.prefixes.for_style(MetricNameStyle::Identity),
            )
            .field("forward_entry_metadata", &self.forward_entry_metadata)
            .finish()
    }
}

impl MetricsPoolHandle {
    /// Return the number of oldest child entries this pool has evicted due to
    /// capacity.
    ///
    /// The count remains available through a retained handle after the parent
    /// has closed.
    pub fn overflow_count(&self) -> u64 {
        self.inner.overflow_count()
    }

    /// Return a handle with an additional prefix path, inflected using the
    /// parent entry's name style.
    ///
    /// Segments must be static because the fully inflected path is interned for
    /// entry descriptors.
    pub fn with_prefix<I>(&self, segments: I) -> Self
    where
        I: IntoIterator<Item = &'static str>,
    {
        Self {
            inner: Arc::clone(&self.inner),
            prefixes: self.prefixes.with_segments(segments),
            forward_entry_metadata: self.forward_entry_metadata,
        }
    }

    /// Return a handle with an additional literal prefix.
    ///
    /// Use this for punctuation-delimited names such as `sdk.request.`.
    pub fn with_exact_prefix(&self, prefix: &'static str) -> Self {
        Self {
            inner: Arc::clone(&self.inner),
            prefixes: self.prefixes.with_exact_prefix(prefix),
            forward_entry_metadata: self.forward_entry_metadata,
        }
    }

    /// Return a handle that forwards child timestamps and [`EntryConfig`] to the
    /// parent entry.
    ///
    /// Pool handles suppress this metadata by default because a child timestamp
    /// or configuration can conflict with the parent's and invalidate the entire
    /// record. Use this only when the child is intended to control entry-level
    /// metadata. Child sample groups remain suppressed.
    pub fn forward_entry_metadata(&self) -> Self {
        Self {
            inner: Arc::clone(&self.inner),
            prefixes: self.prefixes.clone(),
            forward_entry_metadata: true,
        }
    }

    /// Install this pool while `future` is being polled.
    pub fn scope<F>(&self, future: F) -> MetricsPoolScope<F> {
        MetricsPoolScope {
            pool: self.clone(),
            future,
        }
    }

    /// Close `metric` and append it to the pool.
    pub fn append<E>(&self, metric: E)
    where
        E: CloseEntry,
        E::Closed: InflectableEntry<Identity>
            + InflectableEntry<PascalCase>
            + InflectableEntry<SnakeCase>
            + InflectableEntry<KebabCase>
            + Send
            + Sync
            + 'static,
    {
        self.push_closed(metric.close());
    }

    /// Return a guard that closes and appends `metric` when dropped.
    pub fn append_on_drop<E>(&self, metric: E) -> AppendAndCloseOnDrop<E, Self>
    where
        E: CloseEntry,
        E::Closed: InflectableEntry<Identity>
            + InflectableEntry<PascalCase>
            + InflectableEntry<SnakeCase>
            + InflectableEntry<KebabCase>
            + Send
            + Sync
            + 'static,
    {
        append_and_close(metric, self.clone())
    }

    /// Like [`MetricsPoolHandle::append_on_drop`], starting from `E::default()`.
    pub fn append_on_drop_default<E>(&self) -> AppendAndCloseOnDrop<E, Self>
    where
        E: Default + CloseEntry,
        E::Closed: InflectableEntry<Identity>
            + InflectableEntry<PascalCase>
            + InflectableEntry<SnakeCase>
            + InflectableEntry<KebabCase>
            + Send
            + Sync
            + 'static,
    {
        self.append_on_drop(E::default())
    }

    fn push_closed<M>(&self, metric: M)
    where
        M: InflectableEntry<Identity>
            + InflectableEntry<PascalCase>
            + InflectableEntry<SnakeCase>
            + InflectableEntry<KebabCase>
            + Send
            + Sync
            + 'static,
    {
        self.inner.push(BufferedEntry::new(
            metric,
            self.prefixes.clone(),
            self.forward_entry_metadata,
        ));
    }
}

impl<M> EntrySink<RootEntry<M>> for MetricsPoolHandle
where
    M: InflectableEntry<Identity>
        + InflectableEntry<PascalCase>
        + InflectableEntry<SnakeCase>
        + InflectableEntry<KebabCase>
        + Send
        + Sync
        + 'static,
{
    fn append(&self, entry: RootEntry<M>) {
        self.push_closed(entry.into_inner());
    }

    fn flush_async(&self) -> FlushWait {
        FlushWait::ready()
    }
}

struct ScopeGuard;

impl ScopeGuard {
    fn install(pool: MetricsPoolHandle) -> Self {
        CURRENT_POOL.with(|current| current.borrow_mut().push(pool));
        Self
    }
}

impl Drop for ScopeGuard {
    fn drop(&mut self) {
        CURRENT_POOL.with(|current| {
            current.borrow_mut().pop();
        });
    }
}

pin_project_lite::pin_project! {
    /// A future that installs a metrics pool for each poll.
    ///
    /// Returned by [`MetricsPool::scope`] and [`MetricsPoolHandle::scope`].
    #[must_use = "futures do nothing unless polled"]
    pub struct MetricsPoolScope<F> {
        pool: MetricsPoolHandle,
        #[pin]
        future: F,
    }
}

impl<F: Future> Future for MetricsPoolScope<F> {
    type Output = F::Output;

    fn poll(self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<Self::Output> {
        let this = self.project();
        let _scope = ScopeGuard::install(this.pool.clone());
        this.future.poll(cx)
    }
}

/// Closed representation of [`MetricsPool`].
#[doc(hidden)]
pub struct MetricsPoolEntry {
    entries: VecDeque<BufferedEntry>,
}

impl<NS: NameStyle> InflectableEntry<NS> for MetricsPoolEntry {
    /// Emit the pooled children, dropping those superseded by a later child.
    ///
    /// [`MetricsPoolEntry::scan_fields`] determines which children collide; this
    /// pass simply skips them and writes each surviving child unchanged.
    fn write<'a>(&'a self, writer: &mut impl EntryWriter<'a>) {
        let scan = self.scan_fields::<NS>();
        if !scan.field_collisions.is_empty() {
            rate_limited!(
                Duration::from_secs(60),
                tracing::warn!(
                    fields = ?scan.field_collisions,
                    "MetricsPool dropped child entries whose field names collided with a kept child's"
                )
            );
        }

        for (index, entry) in self.entries.iter().enumerate() {
            if scan.losers.contains(&index) {
                #[cfg(debug_assertions)]
                {
                    let mut actual = FieldNames::default();
                    entry.write::<NS>(&mut actual);
                    debug_assert_stable_fields(index, &scan.child_fields[index], &actual.names);
                }
                continue;
            }

            #[cfg(debug_assertions)]
            {
                let mut checked = StableFieldsWriter::new(writer);
                entry.write::<NS>(&mut checked);
                debug_assert_stable_fields(index, &scan.child_fields[index], checked.names());
            }
            #[cfg(not(debug_assertions))]
            entry.write::<NS>(writer);
        }
    }

    // Contributed entries must not implicitly influence the parent sampling policy.
    fn sample_group(
        &self,
    ) -> impl Iterator<Item = metrique::writer::core::entry::SampleGroupElement> {
        std::iter::empty()
    }

    fn descriptors(&self) -> Descriptors<'_> {
        // Descriptors are a promise about the fields this entry will emit. A
        // dropped child breaks that promise, so decline to describe rather than
        // have a descriptor-aware sink pre-register a field that never arrives.
        let scan = self.scan_fields::<NS>();
        if !scan.field_collisions.is_empty() {
            return Descriptors::Unavailable;
        }

        self.entries
            .iter()
            .fold(Descriptors::available(std::iter::empty()), |acc, entry| {
                acc.chain(entry.descriptors::<NS>())
            })
    }
}

impl MetricsPoolEntry {
    /// Count every child's field names, then reconcile them into a plan of which
    /// children survive.
    fn scan_fields<NS: NameStyle>(&self) -> FieldScan {
        let children = self
            .entries
            .iter()
            .map(|entry| {
                let mut fields = FieldNames::default();
                entry.write::<NS>(&mut fields);
                fields.names
            })
            .collect::<Vec<_>>();
        FieldScan::reconcile(children)
    }
}

type NamespacePrefix<NS> =
    <NS as NameStyle>::Inflect<EmptyConstStr, EmptyConstStr, EmptyConstStr, EmptyConstStr>;

fn namespace_prefix<NS: NameStyle>() -> &'static str {
    match const_str_value::<NamespacePrefix<NS>>() {
        Cow::Borrowed(prefix) => prefix,
        Cow::Owned(prefix) => intern_prefix(prefix),
    }
}

/// Which children must be dropped because another kept child claimed one of their
/// field names.
///
/// Collisions are resolved per-child rather than per-field: a child that shares a
/// fully-qualified field name with a kept child is a "loser" and is dropped in its
/// entirety. This prevents "frankenentries" where fields from different children
/// are interleaved into a single emitted entry.
///
/// Survivors are picked by walking children from last to first, keeping a child
/// only if none of its names are already claimed. Walking backwards keeps the
/// familiar "later child wins" outcome for a colliding pair while avoiding a
/// forward pass's failure mode, where a child is dropped by a successor that is
/// itself dropped later, deleting fields no surviving child re-emits.
#[derive(Default)]
struct FieldScan {
    /// The scan-pass field names used to verify later passes in debug builds.
    #[cfg(debug_assertions)]
    child_fields: Vec<HashSet<String>>,
    /// Fully-qualified names that a dropped child shared with a kept one. Reported
    /// in the collision warning; `losers` is what the emit pass acts on.
    field_collisions: BTreeSet<String>,
    /// Indices of children that were superseded and must be dropped wholesale.
    losers: BTreeSet<usize>,
}

impl FieldScan {
    /// Decide which children survive, given each child's field names in child
    /// order.
    fn reconcile(children: Vec<HashSet<String>>) -> Self {
        let mut scan = Self::default();
        let mut claimed: HashSet<&str> = HashSet::new();

        for (index, names) in children.iter().enumerate().rev() {
            let collisions: Vec<&String> = names
                .iter()
                .filter(|name| claimed.contains(name.as_str()))
                .collect();

            if !collisions.is_empty() {
                scan.losers.insert(index);
                scan.field_collisions
                    .extend(collisions.into_iter().cloned());
                // A dropped child claims nothing, so an earlier child writing only
                // its fields still survives.
                continue;
            }

            claimed.extend(names.iter().map(String::as_str));
        }

        #[cfg(debug_assertions)]
        {
            scan.child_fields = children;
        }
        scan
    }
}

/// Records the field names one child writes instead of emitting them.
#[derive(Default)]
struct FieldNames {
    names: HashSet<String>,
}

impl<'a> EntryWriter<'a> for FieldNames {
    fn timestamp(&mut self, _timestamp: SystemTime) {}

    fn value(&mut self, name: impl Into<Cow<'a, str>>, _value: &(impl Value + ?Sized)) {
        self.names.insert(name.into().into_owned());
    }

    fn config(&mut self, _config: &'a dyn EntryConfig) {}
}

#[cfg(debug_assertions)]
fn debug_assert_stable_fields(index: usize, expected: &HashSet<String>, actual: &HashSet<String>) {
    debug_assert_eq!(
        actual, expected,
        "MetricsPool child changed its field names between write passes (child index {index}); pooled entries must emit the same set of field names on every write"
    );
}

/// Forwards one child write while recording its field-name set for a debug-only
/// stability check.
#[cfg(debug_assertions)]
struct StableFieldsWriter<'w, W> {
    inner: &'w mut W,
    names: HashSet<String>,
}

#[cfg(debug_assertions)]
impl<'w, W> StableFieldsWriter<'w, W> {
    fn new(inner: &'w mut W) -> Self {
        Self {
            inner,
            names: HashSet::new(),
        }
    }

    fn names(&self) -> &HashSet<String> {
        &self.names
    }
}

#[cfg(debug_assertions)]
impl<'a, W: EntryWriter<'a>> EntryWriter<'a> for StableFieldsWriter<'_, W> {
    fn timestamp(&mut self, timestamp: SystemTime) {
        self.inner.timestamp(timestamp);
    }

    fn value(&mut self, name: impl Into<Cow<'a, str>>, value: &(impl Value + ?Sized)) {
        let name = name.into();
        self.names.insert(name.as_ref().to_owned());
        self.inner.value(name, value);
    }

    fn config(&mut self, config: &'a dyn EntryConfig) {
        self.inner.config(config);
    }
}

struct BufferedEntry {
    prefixes: PrefixSet,
    forward_entry_metadata: bool,
    entry: StyledEntries,
}

impl BufferedEntry {
    fn new<M>(metric: M, prefixes: PrefixSet, forward_entry_metadata: bool) -> Self
    where
        M: InflectableEntry<Identity>
            + InflectableEntry<PascalCase>
            + InflectableEntry<SnakeCase>
            + InflectableEntry<KebabCase>
            + Send
            + Sync
            + 'static,
    {
        let metric = Arc::new(metric);
        Self {
            prefixes,
            forward_entry_metadata,
            entry: StyledEntries {
                identity: BoxEntry::new(DynamicInflectionEntry {
                    entry: Arc::clone(&metric),
                    name_style: MetricNameStyle::Identity,
                }),
                pascal: BoxEntry::new(DynamicInflectionEntry {
                    entry: Arc::clone(&metric),
                    name_style: MetricNameStyle::PascalCase,
                }),
                snake: BoxEntry::new(DynamicInflectionEntry {
                    entry: Arc::clone(&metric),
                    name_style: MetricNameStyle::SnakeCase,
                }),
                kebab: BoxEntry::new(DynamicInflectionEntry {
                    entry: metric,
                    name_style: MetricNameStyle::KebabCase,
                }),
            },
        }
    }

    fn write<'a, NS: NameStyle>(&'a self, writer: &mut impl EntryWriter<'a>) {
        let style = dynamic_name_style::<NS>();
        let prefix = self.prefix::<NS>(style);
        let entry = self.entry.for_style(style);

        let mut pooled = PooledEntryWriter {
            inner: writer,
            prefix,
            forward_entry_metadata: self.forward_entry_metadata,
        };
        entry.write(&mut pooled);
    }

    fn descriptors<NS: NameStyle>(&self) -> Descriptors<'_> {
        let style = dynamic_name_style::<NS>();
        let prefix = self.prefix::<NS>(style);
        let descriptors = self.entry.for_style(style).descriptors();

        if prefix.is_empty() {
            descriptors
        } else {
            descriptors.map_available(|descriptor| descriptor.with_prefix(prefix))
        }
    }

    fn prefix<NS: NameStyle>(&self, style: MetricNameStyle) -> &'static str {
        let namespace = namespace_prefix::<NS>();
        let handle = self.prefixes.for_style(style);
        match (namespace.is_empty(), handle.is_empty()) {
            (_, true) => namespace,
            (true, false) => handle,
            (false, false) => intern_prefix(format!("{namespace}{handle}")),
        }
    }
}

struct StyledEntries {
    identity: BoxEntry,
    pascal: BoxEntry,
    snake: BoxEntry,
    kebab: BoxEntry,
}

impl StyledEntries {
    fn for_style(&self, style: MetricNameStyle) -> &BoxEntry {
        match style {
            MetricNameStyle::PascalCase => &self.pascal,
            MetricNameStyle::SnakeCase => &self.snake,
            MetricNameStyle::KebabCase => &self.kebab,
            _ => &self.identity,
        }
    }
}

/// Suppresses child entry metadata unless explicitly enabled and prepends the
/// producer's prefix to each field name.
struct PooledEntryWriter<'a, W> {
    inner: &'a mut W,
    prefix: &'static str,
    forward_entry_metadata: bool,
}

impl<'a, W: EntryWriter<'a>> EntryWriter<'a> for PooledEntryWriter<'_, W> {
    fn timestamp(&mut self, timestamp: std::time::SystemTime) {
        if self.forward_entry_metadata {
            self.inner.timestamp(timestamp);
        }
    }

    fn value(&mut self, name: impl Into<Cow<'a, str>>, value: &(impl Value + ?Sized)) {
        let name = name.into();
        if self.prefix.is_empty() {
            self.inner.value(name, value);
            return;
        }

        let mut prefixed = String::with_capacity(self.prefix.len() + name.len());
        prefixed.push_str(self.prefix);
        prefixed.push_str(name.as_ref());
        self.inner.value(Cow::Owned(prefixed), value);
    }

    fn config(&mut self, config: &'a dyn EntryConfig) {
        if self.forward_entry_metadata {
            self.inner.config(config);
        }
    }
}

/// Capture the current metrics pool and propagate it while `future` is polled.
///
/// Capture happens synchronously when this function is called, before an
/// executor can detach the returned future. When a pool is captured, it is
/// installed for every poll using [`MetricsPoolHandle::scope`]. If no pool is
/// current at capture time, the input future is polled without adding a scope.
///
/// This wrapper is executor-independent, but it must be applied at a spawn site
/// controlled by the caller; it cannot affect tasks spawned internally by a
/// third-party library.
///
/// ```no_run
/// use metrique_util::{MetricsPool, propagate_current};
///
/// # async fn example() {
/// # let pool = MetricsPool::new();
/// pool.handle()
///     .scope(async {
///         tokio::spawn(propagate_current(async {
///             let pool = MetricsPool::current().expect("pool was propagated");
///             // Detached work can append through `pool` here.
///             # drop(pool);
///         }))
///         .await
///         .unwrap();
///     })
///     .await;
/// # }
/// ```
#[must_use = "futures do nothing unless polled"]
pub fn propagate_current<F: Future>(future: F) -> impl Future<Output = F::Output> {
    let pool = MetricsPool::current();
    async move {
        match pool {
            Some(pool) => pool.scope(future).await,
            None => future.await,
        }
    }
}

/// Run `future` with `pool` available through [`MetricsPool::current`].
pub fn with_metrics_pool<F>(pool: MetricsPoolHandle, future: F) -> MetricsPoolScope<F> {
    pool.scope(future)
}
