// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

//! Collects metrics from decoupled producers and flattens them into one parent entry.
//!
//! A pool lets code that cannot name the parent metric type—such as middleware,
//! SDK interceptors, or libraries—contribute child metrics. To include a pool in
//! an entry, annotate its containing field with `#[metrics(flatten)]`; that
//! annotation tells `#[metrics]` to emit the pool's fields in the parent entry.
//! Producers append child metrics through a [`MetricsPoolHandle`].
//!
//! ```no_run
//! use metrique::unit_of_work::metrics;
//! use metrique_util::MetricsPool;
//!
//! #[metrics(rename_all = "PascalCase")]
//! struct RequestMetrics {
//!     operation: &'static str,
//!     #[metrics(flatten)]
//!     pool: MetricsPool,
//! }
//!
//! #[metrics(rename_all = "PascalCase")]
//! struct AttemptMetrics {
//!     retry_count: u32,
//! }
//!
//! # fn example(sink: impl metrique::writer::EntrySink<metrique::RootEntry<RequestMetricsEntry>> + Send + Sync + 'static) {
//! let request = RequestMetrics { operation: "PutObject", pool: MetricsPool::new() }
//!     .append_on_drop(sink);
//!
//! // A producer can keep this handle without depending on `RequestMetrics`.
//! request.pool.handle().with_prefix(["sdk", "s3"])
//!     .append(AttemptMetrics { retry_count: 2 });
//!
//! // Dropping `request` emits `Operation` and `SdkS3RetryCount`.
//! # }
//! ```
//!
//! # Scoped access
//!
//! Pass a handle explicitly, or use [`with_metrics_pool`] to make one available
//! through [`MetricsPool::current`] while a future is polled. This scope is tied
//! to future polls, not to a thread or logical request:
//!
//! - Spawned tasks start without the scope. Wrap their future with
//!   [`propagate_current`] at the spawn site, or capture a handle and move it into
//!   detached work explicitly.
//! - `spawn_blocking` closures and threads cannot use a future wrapper; capture a
//!   handle before spawning and move it into the closure.
//! - Blocking inside a scoped poll can expose the pool to unrelated work running
//!   on that thread, corrupting attribution. Pass handles explicitly instead.
//!
//! `MetricsPool::current` returns `None` both when no pool is installed and when
//! work was detached from a scope. Producers should use a standalone sink in
//! that case rather than discard the metric.
//!
//! # Naming and prefixes
//!
//! [`MetricsPoolHandle::with_prefix`] follows the parent name style: the same
//! prefix becomes `SdkS3RetryCount` in `PascalCase` and `sdk_s3_retry_count` in
//! `snake_case`. Use [`MetricsPoolHandle::with_exact_prefix`] for literal
//! prefixes such as `sdk.request.`.
//!
//! # Parent lifetime
//!
//! Closing the parent closes the pool and drains the children collected so far.
//! Appends after that point are discarded with a rate-limited warning, so child
//! producers and append-on-drop guards must finish before the parent guard drops.
//!
//! # Capacity and overflow
//!
//! A pool retains at most 128 child entries by default. Each append consumes one
//! slot regardless of how many fields the child writes. When the pool is full,
//! appending never waits for free capacity: the oldest child is evicted and a
//! rate-limited warning is emitted. Use [`MetricsPool::builder`] to configure
//! the capacity and [`MetricsPool::overflow_count`] or
//! [`MetricsPoolHandle::overflow_count`] to observe evictions.
//!
//! # Entry metadata and sampling
//!
//! Pooled children contribute fields but do not replace parent entry metadata by
//! default: child timestamps and [`EntryConfig`] calls are suppressed. A producer
//! can deliberately forward them through
//! [`MetricsPoolHandle::forward_entry_metadata`], but a second timestamp or
//! incompatible configuration can invalidate the parent record. Child sample
//! groups are always ignored and cannot change the parent's sampling policy.
//!
//! # Collision policy
//!
//! Collisions are compared using fully inflected field names among children in
//! the same pool. If two children collide, the later child wins and the earlier
//! child is dropped in full, preventing fields from separate attempts from being
//! combined into a record that never existed. If one child writes a name more
//! than once, only its final write is emitted.
//!
//! Collision handling writes children more than once. A closed child must emit
//! the same multiset of field names on every write. Values and field order may
//! change, but interior mutability must not change which names are present or how
//! often a name is written. Entries generated by `#[metrics]` satisfy this unless
//! they flatten a custom entry that violates the requirement. Debug builds assert
//! when a child changes its field names between passes.
//!
//! The pool cannot detect collisions with ordinary parent fields or other
//! flattened components. Give producers distinct prefixes from one another and
//! from the parent entry. Collision detection also replays child entries, so use
//! a pool at integration boundaries where the parent cannot name child types;
//! prefer statically typed flattened fields otherwise.

use core::future::Future;
use core::pin::Pin;
use core::task::{Context, Poll};
use std::borrow::Cow;
use std::cell::RefCell;
use std::collections::{BTreeSet, HashMap, HashSet, VecDeque};
use std::fmt::Debug;
use std::sync::atomic::{AtomicU64, Ordering};
use std::sync::{Arc, Mutex, OnceLock};
use std::time::{Duration, SystemTime};

use metrique::writer::rate_limit::rate_limited;
use metrique::writer::sink::FlushWait;
use metrique::writer::{
    BoxEntry, Entry, EntryConfig, EntrySink, EntryWriter, Value, core::Descriptors,
};
use metrique::{
    AppendAndCloseOnDrop, CloseValue, Identity, InflectableEntry, KebabCase, NameStyle, PascalCase,
    RootEntry, SnakeCase, append_and_close,
    concat::{EmptyConstStr, const_str_value},
};
use metrique_core::CloseEntry;
use metrique_core::case_convert::CaseStyle;

const DEFAULT_METRICS_POOL_CAPACITY: usize = 128;

thread_local! {
    static CURRENT_POOL: RefCell<Vec<MetricsPoolHandle>> = const { RefCell::new(Vec::new()) };
}

fn intern_prefix(prefix: String) -> &'static str {
    static INTERNED: OnceLock<Mutex<HashMap<String, &'static str>>> = OnceLock::new();
    let interned = INTERNED.get_or_init(|| Mutex::new(HashMap::new()));
    let mut interned = interned.lock().unwrap();

    if let Some(existing) = interned.get(prefix.as_str()) {
        return existing;
    }

    let leaked = Box::leak(prefix.clone().into_boxed_str());
    interned.insert(prefix, leaked);
    leaked
}

#[derive(Clone, Copy, Debug)]
enum RuntimeStyle {
    Identity,
    PascalCase,
    SnakeCase,
    KebabCase,
}

impl RuntimeStyle {
    fn for_ns<NS: NameStyle>() -> Self {
        match NS::DESCRIPTOR_STYLE_INDEX {
            1 => Self::PascalCase,
            2 => Self::SnakeCase,
            3 => Self::KebabCase,
            _ => Self::Identity,
        }
    }

    /// The [`CaseStyle`] the `#[metrics]` macro uses for this name style, so a
    /// runtime prefix inflects exactly like a compile-time field name.
    fn case_style(self) -> CaseStyle {
        match self {
            Self::Identity => CaseStyle::Preserve,
            Self::PascalCase => CaseStyle::Pascal,
            Self::SnakeCase => CaseStyle::Snake,
            Self::KebabCase => CaseStyle::Kebab,
        }
    }

    fn prefix_segment(self, segment: &str) -> String {
        // `apply_prefix` appends the trailing `_`/`-` for the delimited styles and
        // leaves the delimiter-free ones alone.
        let mut prefix = self.case_style().apply_prefix(segment);
        // `Preserve` adds no delimiter, because a preserved *field* prefix is taken
        // verbatim. A pool segment is a path component, not a literal
        // (`with_exact_prefix` is the literal form), so it still needs a separator:
        // `["sdk", "s3"]` must not become `sdks3`.
        if matches!(self, Self::Identity) && !prefix.ends_with('_') && !prefix.ends_with('-') {
            prefix.push('_');
        }
        prefix
    }
}

#[derive(Clone, Copy, Debug)]
struct PrefixSet {
    identity: &'static str,
    pascal: &'static str,
    snake: &'static str,
    kebab: &'static str,
}

impl PrefixSet {
    fn empty() -> Self {
        Self {
            identity: "",
            pascal: "",
            snake: "",
            kebab: "",
        }
    }

    fn with_segments<I>(self, segments: I) -> Self
    where
        I: IntoIterator<Item = &'static str>,
    {
        let mut identity = self.identity.to_string();
        let mut pascal = self.pascal.to_string();
        let mut snake = self.snake.to_string();
        let mut kebab = self.kebab.to_string();

        for segment in segments {
            if segment.is_empty() {
                continue;
            }

            identity.push_str(&RuntimeStyle::Identity.prefix_segment(segment));
            pascal.push_str(&RuntimeStyle::PascalCase.prefix_segment(segment));
            snake.push_str(&RuntimeStyle::SnakeCase.prefix_segment(segment));
            kebab.push_str(&RuntimeStyle::KebabCase.prefix_segment(segment));
        }

        Self {
            identity: intern_prefix(identity),
            pascal: intern_prefix(pascal),
            snake: intern_prefix(snake),
            kebab: intern_prefix(kebab),
        }
    }

    fn with_exact_prefix(self, prefix: &'static str) -> Self {
        fn append(existing: &'static str, prefix: &'static str) -> &'static str {
            match (existing.is_empty(), prefix.is_empty()) {
                (_, true) => existing,
                (true, false) => prefix,
                (false, false) => intern_prefix(format!("{existing}{prefix}")),
            }
        }

        Self {
            identity: append(self.identity, prefix),
            pascal: append(self.pascal, prefix),
            snake: append(self.snake, prefix),
            kebab: append(self.kebab, prefix),
        }
    }

    fn for_style(self, style: RuntimeStyle) -> &'static str {
        match style {
            RuntimeStyle::Identity => self.identity,
            RuntimeStyle::PascalCase => self.pascal,
            RuntimeStyle::SnakeCase => self.snake,
            RuntimeStyle::KebabCase => self.kebab,
        }
    }
}

struct MetricsPoolInner {
    entries: Mutex<Option<VecDeque<BufferedEntry>>>,
    capacity: usize,
    overflow_count: AtomicU64,
}

impl MetricsPoolInner {
    fn new(capacity: usize) -> Self {
        Self {
            entries: Mutex::new(Some(VecDeque::new())),
            capacity,
            overflow_count: AtomicU64::new(0),
        }
    }

    fn push(&self, entry: BufferedEntry) {
        enum PushOutcome {
            Appended,
            AppendedWithEviction {
                _oldest: BufferedEntry,
                overflow_count: u64,
            },
            Closed {
                _rejected: BufferedEntry,
            },
        }

        let outcome = {
            let mut state = self.entries.lock().unwrap();
            match state.as_mut() {
                Some(entries) => {
                    let oldest = if entries.len() >= self.capacity {
                        entries.pop_front()
                    } else {
                        None
                    };
                    entries.push_back(entry);
                    match oldest {
                        Some(oldest) => PushOutcome::AppendedWithEviction {
                            _oldest: oldest,
                            overflow_count: self.overflow_count.fetch_add(1, Ordering::Relaxed) + 1,
                        },
                        None => PushOutcome::Appended,
                    }
                }
                None => PushOutcome::Closed { _rejected: entry },
            }
        };

        // Drop discarded children after unlocking: a child's destructor may
        // append to this pool and would deadlock trying to reacquire the mutex.
        match outcome {
            PushOutcome::Appended => {}
            PushOutcome::AppendedWithEviction { overflow_count, .. } => {
                rate_limited!(
                    Duration::from_secs(1),
                    tracing::warn!(
                        capacity = self.capacity,
                        overflow_count,
                        "MetricsPool is full; dropped the oldest child entry"
                    )
                );
            }
            PushOutcome::Closed { .. } => {
                rate_limited!(
                    Duration::from_secs(60),
                    tracing::warn!(
                        "MetricsPool dropped an entry appended after close; parent closed before producers finished"
                    )
                );
            }
        }
    }

    fn take(&self) -> VecDeque<BufferedEntry> {
        self.entries.lock().unwrap().take().unwrap_or_default()
    }

    fn overflow_count(&self) -> u64 {
        self.overflow_count.load(Ordering::Relaxed)
    }
}

/// Configures a [`MetricsPool`].
#[derive(Clone, Copy, Debug)]
pub struct MetricsPoolBuilder {
    capacity: usize,
}

impl MetricsPoolBuilder {
    /// Create a builder with the default capacity of 128 child entries.
    pub fn new() -> Self {
        Self::default()
    }

    /// Set the maximum number of child entries retained by the pool.
    ///
    /// Each append consumes one slot regardless of how many fields that child
    /// writes. Once the pool is full, appending a child evicts the oldest child.
    ///
    /// # Panics
    ///
    /// Panics if `capacity` is zero.
    pub fn capacity(mut self, capacity: usize) -> Self {
        assert!(
            capacity > 0,
            "MetricsPool capacity must be greater than zero"
        );
        self.capacity = capacity;
        self
    }

    /// Build a metrics pool with this configuration.
    pub fn build(self) -> MetricsPool {
        MetricsPool {
            inner: Arc::new(MetricsPoolInner::new(self.capacity)),
        }
    }
}

impl Default for MetricsPoolBuilder {
    fn default() -> Self {
        Self {
            capacity: DEFAULT_METRICS_POOL_CAPACITY,
        }
    }
}

/// The request-owned collection point for pooled child metrics.
///
/// Store one pool in the parent metric entry under `#[metrics(flatten)]`, then
/// distribute [`MetricsPoolHandle`]s to producers. A default pool retains the
/// latest 128 child entries. Closing the parent consumes the pool and emits the
/// children collected before that close; later appends are discarded.
///
/// See the [`metrics_pool`](crate::metrics_pool) module guide for scoped access,
/// naming, metadata, lifetime, and collision policies.
pub struct MetricsPool {
    inner: Arc<MetricsPoolInner>,
}

impl MetricsPool {
    /// The maximum number of child entries retained by a default pool.
    pub const DEFAULT_CAPACITY: usize = DEFAULT_METRICS_POOL_CAPACITY;

    /// Create an empty metrics pool with capacity for 128 child entries.
    pub fn new() -> Self {
        Self::builder().build()
    }

    /// Create a builder for configuring a metrics pool.
    pub fn builder() -> MetricsPoolBuilder {
        MetricsPoolBuilder::new()
    }

    /// Return the maximum number of child entries this pool retains.
    pub fn capacity(&self) -> usize {
        self.inner.capacity
    }

    /// Return the number of oldest child entries evicted due to capacity.
    pub fn overflow_count(&self) -> u64 {
        self.inner.overflow_count()
    }

    /// Return a cloneable handle to this pool.
    pub fn handle(&self) -> MetricsPoolHandle {
        MetricsPoolHandle {
            inner: Arc::clone(&self.inner),
            prefixes: PrefixSet::empty(),
            forward_entry_metadata: false,
        }
    }

    /// Install this pool while `future` is being polled.
    pub fn scope<F>(&self, future: F) -> MetricsPoolScope<F> {
        self.handle().scope(future)
    }

    /// Return the pool installed for the current future poll, if any.
    ///
    /// The scope does not cross a task spawn, blocking-task spawn, or thread
    /// boundary. `None` therefore means either that no pool is installed or that
    /// this work was detached from one. Pass a handle into detached work, and use
    /// a standalone sink when no pool is available.
    pub fn current() -> Option<MetricsPoolHandle> {
        CURRENT_POOL.with(|current| current.borrow().last().cloned())
    }
}

impl Default for MetricsPool {
    fn default() -> Self {
        Self::new()
    }
}

impl Debug for MetricsPool {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let entry_count = self
            .inner
            .entries
            .lock()
            .unwrap()
            .as_ref()
            .map_or(0, VecDeque::len);

        f.debug_struct("MetricsPool")
            .field("entry_count", &entry_count)
            .field("capacity", &self.inner.capacity)
            .field("overflow_count", &self.inner.overflow_count())
            .finish()
    }
}

impl CloseValue for MetricsPool {
    type Closed = MetricsPoolEntry;

    fn close(self) -> Self::Closed {
        MetricsPoolEntry {
            entries: self.inner.take(),
        }
    }
}

/// Cloneable producer handle for a [`MetricsPool`].
#[derive(Clone)]
pub struct MetricsPoolHandle {
    inner: Arc<MetricsPoolInner>,
    prefixes: PrefixSet,
    forward_entry_metadata: bool,
}

impl Debug for MetricsPoolHandle {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("MetricsPoolHandle")
            .field("identity_prefix", &self.prefixes.identity)
            .field("forward_entry_metadata", &self.forward_entry_metadata)
            .finish()
    }
}

impl MetricsPoolHandle {
    /// Return the number of oldest child entries this pool has evicted due to
    /// capacity.
    ///
    /// The count remains available through a retained handle after the parent
    /// has closed.
    pub fn overflow_count(&self) -> u64 {
        self.inner.overflow_count()
    }

    /// Return a handle with an additional prefix path, inflected using the
    /// parent entry's name style.
    ///
    /// Segments must be static because the fully inflected path is interned for
    /// entry descriptors.
    pub fn with_prefix<I>(&self, segments: I) -> Self
    where
        I: IntoIterator<Item = &'static str>,
    {
        Self {
            inner: Arc::clone(&self.inner),
            prefixes: self.prefixes.with_segments(segments),
            forward_entry_metadata: self.forward_entry_metadata,
        }
    }

    /// Return a handle with an additional literal prefix.
    ///
    /// Use this for punctuation-delimited names such as `sdk.request.`.
    pub fn with_exact_prefix(&self, prefix: &'static str) -> Self {
        Self {
            inner: Arc::clone(&self.inner),
            prefixes: self.prefixes.with_exact_prefix(prefix),
            forward_entry_metadata: self.forward_entry_metadata,
        }
    }

    /// Return a handle that forwards child timestamps and [`EntryConfig`] to the
    /// parent entry.
    ///
    /// Pool handles suppress this metadata by default because a child timestamp
    /// or configuration can conflict with the parent's and invalidate the entire
    /// record. Use this only when the child is intended to control entry-level
    /// metadata. Child sample groups remain suppressed.
    pub fn forward_entry_metadata(&self) -> Self {
        Self {
            inner: Arc::clone(&self.inner),
            prefixes: self.prefixes,
            forward_entry_metadata: true,
        }
    }

    /// Install this pool while `future` is being polled.
    pub fn scope<F>(&self, future: F) -> MetricsPoolScope<F> {
        MetricsPoolScope {
            pool: self.clone(),
            future,
        }
    }

    /// Close `metric` and append it to the pool.
    pub fn append<E>(&self, metric: E)
    where
        E: CloseEntry + Send + Sync + 'static,
        E::Closed: InflectableEntry<Identity>
            + InflectableEntry<PascalCase>
            + InflectableEntry<SnakeCase>
            + InflectableEntry<KebabCase>
            + Send
            + Sync
            + 'static,
    {
        self.push_closed(metric.close());
    }

    /// Return a guard that closes and appends `metric` when dropped.
    pub fn append_on_drop<E>(&self, metric: E) -> AppendAndCloseOnDrop<E, Self>
    where
        E: CloseEntry + Send + Sync + 'static,
        E::Closed: InflectableEntry<Identity>
            + InflectableEntry<PascalCase>
            + InflectableEntry<SnakeCase>
            + InflectableEntry<KebabCase>
            + Send
            + Sync
            + 'static,
    {
        append_and_close(metric, self.clone())
    }

    /// Like [`MetricsPoolHandle::append_on_drop`], starting from `E::default()`.
    pub fn append_on_drop_default<E>(&self) -> AppendAndCloseOnDrop<E, Self>
    where
        E: Default + CloseEntry + Send + Sync + 'static,
        E::Closed: InflectableEntry<Identity>
            + InflectableEntry<PascalCase>
            + InflectableEntry<SnakeCase>
            + InflectableEntry<KebabCase>
            + Send
            + Sync
            + 'static,
    {
        self.append_on_drop(E::default())
    }

    fn push_closed<M>(&self, metric: M)
    where
        M: InflectableEntry<Identity>
            + InflectableEntry<PascalCase>
            + InflectableEntry<SnakeCase>
            + InflectableEntry<KebabCase>
            + Send
            + Sync
            + 'static,
    {
        self.inner.push(BufferedEntry::new(
            metric,
            self.prefixes,
            self.forward_entry_metadata,
        ));
    }
}

impl<M> EntrySink<RootEntry<M>> for MetricsPoolHandle
where
    M: InflectableEntry<Identity>
        + InflectableEntry<PascalCase>
        + InflectableEntry<SnakeCase>
        + InflectableEntry<KebabCase>
        + Send
        + Sync
        + 'static,
{
    fn append(&self, entry: RootEntry<M>) {
        self.push_closed(entry.into_inner());
    }

    fn flush_async(&self) -> FlushWait {
        FlushWait::ready()
    }
}

struct ScopeGuard;

impl ScopeGuard {
    fn install(pool: MetricsPoolHandle) -> Self {
        CURRENT_POOL.with(|current| current.borrow_mut().push(pool));
        Self
    }
}

impl Drop for ScopeGuard {
    fn drop(&mut self) {
        CURRENT_POOL.with(|current| {
            current.borrow_mut().pop();
        });
    }
}

/// A future that installs a metrics pool for each poll.
///
/// Returned by [`MetricsPool::scope`] and [`MetricsPoolHandle::scope`].
#[must_use = "futures do nothing unless polled"]
pub struct MetricsPoolScope<F> {
    pool: MetricsPoolHandle,
    future: F,
}

impl<F: Future> Future for MetricsPoolScope<F> {
    type Output = F::Output;

    fn poll(self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<Self::Output> {
        // Safety: once `self` is pinned, `future` is never moved again.
        let this = unsafe { self.get_unchecked_mut() };
        let _scope = ScopeGuard::install(this.pool.clone());
        // Safety: `future` stays pinned for the lifetime of `self`.
        unsafe { Pin::new_unchecked(&mut this.future) }.poll(cx)
    }
}

/// Closed representation of [`MetricsPool`].
#[doc(hidden)]
pub struct MetricsPoolEntry {
    entries: VecDeque<BufferedEntry>,
}

impl<NS: NameStyle> InflectableEntry<NS> for MetricsPoolEntry {
    /// Emit the pooled children, dropping those superseded by a later child.
    ///
    /// [`MetricsPoolEntry::scan_fields`] determines which children collide; this
    /// pass simply skips them. A surviving child is forwarded straight to `writer`,
    /// unless that child repeats a field name, in which case it alone is routed
    /// through a [`LastWinsEntryWriter`].
    ///
    /// Each surviving child is written twice (once to scan, once to emit) and a
    /// repeating child a third time, to count its names. A child must write the
    /// same multiset of field names every pass, which children generated by
    /// `#[metrics]` do. Values and field order may differ, but interior mutability
    /// must not change name presence or repetition counts. Debug builds assert
    /// this invariant; release builds rely on it. Side effects in a child's
    /// `write` run once per pass.
    fn write<'a>(&'a self, writer: &mut impl EntryWriter<'a>) {
        let scan = self.scan_fields::<NS>();
        if !scan.field_collisions.is_empty() {
            rate_limited!(
                Duration::from_secs(60),
                tracing::warn!(
                    fields = ?scan.field_collisions,
                    "MetricsPool dropped child entries whose field names collided with a kept child's"
                )
            );
        }

        for (index, entry) in self.entries.iter().enumerate() {
            if scan.losers.contains(&index) {
                #[cfg(debug_assertions)]
                {
                    let mut actual = RepeatCount::default();
                    entry.write::<NS>(&mut actual);
                    debug_assert_stable_fields(index, &scan.child_fields[index], &actual.counts);
                }
                continue;
            }

            // This child writes each name once, so every field can go straight
            // through. Children that repeat a name do not affect this one.
            if !scan.repeating_children.contains(&index) {
                #[cfg(debug_assertions)]
                {
                    let mut checked = StableFieldsWriter::new(writer);
                    entry.write::<NS>(&mut checked);
                    debug_assert_stable_fields(index, &scan.child_fields[index], checked.counts());
                }
                #[cfg(not(debug_assertions))]
                entry.write::<NS>(writer);
                continue;
            }

            // Keeping the *last* write of a repeated name needs lookahead: whether
            // another write of that name is still coming. `scan` records which
            // children repeat a name but not how often, so count this child's names
            // here, paying for a map only where one is needed.
            let mut counts = RepeatCount::default();
            entry.write::<NS>(&mut counts);
            #[cfg(debug_assertions)]
            debug_assert_stable_fields(index, &scan.child_fields[index], &counts.counts);

            let mut last_wins = LastWinsEntryWriter {
                inner: writer,
                remaining: counts.counts,
            };
            #[cfg(debug_assertions)]
            {
                let mut checked = StableFieldsWriter::new(&mut last_wins);
                entry.write::<NS>(&mut checked);
                debug_assert_stable_fields(index, &scan.child_fields[index], checked.counts());
            }
            #[cfg(not(debug_assertions))]
            entry.write::<NS>(&mut last_wins);
        }
    }

    // Contributed entries must not implicitly influence the parent sampling policy.
    fn sample_group(
        &self,
    ) -> impl Iterator<Item = metrique::writer::core::entry::SampleGroupElement> {
        std::iter::empty()
    }

    fn descriptors(&self) -> Descriptors<'_> {
        // Descriptors are a promise about the fields this entry will emit. Any pool
        // state that makes `write` emit fewer fields than the children describe (a
        // dropped child, or a repeated name emitted once) breaks that promise, so
        // decline to describe rather than have a descriptor-aware sink pre-register
        // a field that never arrives.
        let scan = self.scan_fields::<NS>();
        if !scan.field_collisions.is_empty() || !scan.repeating_children.is_empty() {
            return Descriptors::Unavailable;
        }

        self.entries
            .iter()
            .fold(Descriptors::available(std::iter::empty()), |acc, entry| {
                acc.chain(entry.descriptors::<NS>())
            })
    }
}

impl MetricsPoolEntry {
    /// Count every child's field names, then reconcile them into a plan of which
    /// children survive.
    fn scan_fields<NS: NameStyle>(&self) -> FieldScan {
        let children = self
            .entries
            .iter()
            .map(|entry| {
                let mut counts = RepeatCount::default();
                entry.write::<NS>(&mut counts);
                counts.counts
            })
            .collect::<Vec<_>>();
        FieldScan::reconcile(children)
    }
}

type NamespacePrefix<NS> =
    <NS as NameStyle>::Inflect<EmptyConstStr, EmptyConstStr, EmptyConstStr, EmptyConstStr>;

fn namespace_prefix<NS: NameStyle>() -> &'static str {
    match const_str_value::<NamespacePrefix<NS>>() {
        Cow::Borrowed(prefix) => prefix,
        Cow::Owned(prefix) => intern_prefix(prefix),
    }
}

/// Which children must be dropped because another kept child claimed one of their
/// field names.
///
/// Collisions are resolved per-child rather than per-field: a child that shares a
/// fully-qualified field name with a kept child is a "loser" and is dropped in its
/// entirety. This prevents "frankenentries" where fields from different children
/// are interleaved into a single emitted entry.
///
/// Survivors are picked by walking children from last to first, keeping a child
/// only if none of its names are already claimed. Walking backwards keeps the
/// familiar "later child wins" outcome for a colliding pair while avoiding a
/// forward pass's failure mode, where a child is dropped by a successor that is
/// itself dropped later, deleting fields no surviving child re-emits.
#[derive(Default)]
struct FieldScan {
    /// The scan-pass field-name counts used to verify later passes in debug builds.
    #[cfg(debug_assertions)]
    child_fields: Vec<HashMap<String, usize>>,
    /// Fully-qualified names that a dropped child shared with a kept one. Reported
    /// in the collision warning; `losers` is what the emit pass acts on.
    field_collisions: BTreeSet<String>,
    /// Indices of children that were superseded and must be dropped wholesale.
    losers: BTreeSet<usize>,
    /// Indices of children that wrote the same field name more than once. These
    /// are the only children that need a [`LastWinsEntryWriter`] on the emit pass.
    repeating_children: BTreeSet<usize>,
}

impl FieldScan {
    /// Decide which children survive, given each child's field-name counts in
    /// child order.
    fn reconcile(children: Vec<HashMap<String, usize>>) -> Self {
        let mut scan = Self::default();
        let mut claimed: HashSet<&str> = HashSet::new();

        for (index, names) in children.iter().enumerate().rev() {
            let collisions: Vec<&String> = names
                .keys()
                .filter(|name| claimed.contains(name.as_str()))
                .collect();

            if !collisions.is_empty() {
                scan.losers.insert(index);
                scan.field_collisions
                    .extend(collisions.into_iter().cloned());
                // A dropped child claims nothing, so an earlier child writing only
                // its fields still survives.
                continue;
            }

            // One child writing the same name twice is not a cross-child
            // collision; the emit pass keeps that child's last write.
            if names.values().any(|&count| count > 1) {
                scan.repeating_children.insert(index);
            }
            claimed.extend(names.keys().map(String::as_str));
        }

        #[cfg(debug_assertions)]
        {
            scan.child_fields = children;
        }
        scan
    }
}

/// Records the field names one child writes, and how many times, instead of
/// emitting them.
///
/// Used both to reconcile cross-child collisions and to find the final write of a
/// repeated name, which is the one [`LastWinsEntryWriter`] emits.
#[derive(Default)]
struct RepeatCount {
    counts: HashMap<String, usize>,
}

impl<'a> EntryWriter<'a> for RepeatCount {
    fn timestamp(&mut self, _timestamp: SystemTime) {}

    fn value(&mut self, name: impl Into<Cow<'a, str>>, _value: &(impl Value + ?Sized)) {
        *self.counts.entry(name.into().into_owned()).or_default() += 1;
    }

    fn config(&mut self, _config: &'a dyn EntryConfig) {}
}

#[cfg(debug_assertions)]
fn debug_assert_stable_fields(
    index: usize,
    expected: &HashMap<String, usize>,
    actual: &HashMap<String, usize>,
) {
    debug_assert_eq!(
        actual, expected,
        "MetricsPool child changed its field names between write passes (child index {index}); pooled entries must emit the same field names the same number of times on every write"
    );
}

/// Forwards one child write while recording its field-name multiset for a
/// debug-only stability check.
#[cfg(debug_assertions)]
struct StableFieldsWriter<'w, W> {
    inner: &'w mut W,
    counts: HashMap<String, usize>,
}

#[cfg(debug_assertions)]
impl<'w, W> StableFieldsWriter<'w, W> {
    fn new(inner: &'w mut W) -> Self {
        Self {
            inner,
            counts: HashMap::new(),
        }
    }

    fn counts(&self) -> &HashMap<String, usize> {
        &self.counts
    }
}

#[cfg(debug_assertions)]
impl<'a, W: EntryWriter<'a>> EntryWriter<'a> for StableFieldsWriter<'_, W> {
    fn timestamp(&mut self, timestamp: SystemTime) {
        self.inner.timestamp(timestamp);
    }

    fn value(&mut self, name: impl Into<Cow<'a, str>>, value: &(impl Value + ?Sized)) {
        let name = name.into();
        *self.counts.entry(name.as_ref().to_owned()).or_default() += 1;
        self.inner.value(name, value);
    }

    fn config(&mut self, config: &'a dyn EntryConfig) {
        self.inner.config(config);
    }
}

/// Emits only the last write of each field name for the child it wraps.
///
/// Cross-child collisions are handled by dropping whole children, so among the
/// children that survive each fully-qualified name has exactly one writer. This
/// writer therefore only has to resolve names a single child repeats, and needs
/// no knowledge of the other children.
///
/// `remaining` starts as that child's field-name counts and is decremented as the
/// child is replayed; a name is forwarded on the write that brings its count to
/// zero, which is its final write. Exactly one write of a name can ever be
/// forwarded: the EMF formatter rejects an entire entry containing a duplicate
/// field, so emitting a name twice would discard the whole metric record.
struct LastWinsEntryWriter<'w, W> {
    inner: &'w mut W,
    remaining: HashMap<String, usize>,
}

impl<'a, W: EntryWriter<'a>> EntryWriter<'a> for LastWinsEntryWriter<'_, W> {
    fn timestamp(&mut self, timestamp: SystemTime) {
        self.inner.timestamp(timestamp);
    }

    fn value(&mut self, name: impl Into<Cow<'a, str>>, value: &(impl Value + ?Sized)) {
        let name = name.into();
        let mut uncounted = false;
        let emit = match self.remaining.get_mut(name.as_ref()) {
            Some(remaining) => {
                // Forward the final write, skip the ones it supersedes, and skip
                // anything past the count so a name is never emitted twice.
                let last = *remaining == 1;
                *remaining = remaining.saturating_sub(1);
                last
            }
            // Only reachable if the child's output changed since it was counted a
            // moment ago. Forward this write and record the name so that a later
            // one cannot duplicate it.
            None => {
                uncounted = true;
                true
            }
        };

        if uncounted {
            self.remaining.insert(name.as_ref().to_owned(), 0);
        }

        if emit {
            self.inner.value(name, value);
        }
    }

    fn config(&mut self, config: &'a dyn EntryConfig) {
        self.inner.config(config);
    }
}

struct BufferedEntry {
    prefixes: PrefixSet,
    forward_entry_metadata: bool,
    entry: StyledEntries,
}

impl BufferedEntry {
    fn new<M>(metric: M, prefixes: PrefixSet, forward_entry_metadata: bool) -> Self
    where
        M: InflectableEntry<Identity>
            + InflectableEntry<PascalCase>
            + InflectableEntry<SnakeCase>
            + InflectableEntry<KebabCase>
            + Send
            + Sync
            + 'static,
    {
        let metric = Arc::new(metric);
        Self {
            prefixes,
            forward_entry_metadata,
            entry: StyledEntries {
                identity: BoxEntry::new(RuntimeInflectedEntry::new(
                    Arc::clone(&metric),
                    RuntimeStyle::Identity,
                )),
                pascal: BoxEntry::new(RuntimeInflectedEntry::new(
                    Arc::clone(&metric),
                    RuntimeStyle::PascalCase,
                )),
                snake: BoxEntry::new(RuntimeInflectedEntry::new(
                    Arc::clone(&metric),
                    RuntimeStyle::SnakeCase,
                )),
                kebab: BoxEntry::new(RuntimeInflectedEntry::new(metric, RuntimeStyle::KebabCase)),
            },
        }
    }

    fn write<'a, NS: NameStyle>(&'a self, writer: &mut impl EntryWriter<'a>) {
        let style = RuntimeStyle::for_ns::<NS>();
        let prefix = self.prefix::<NS>(style);
        let entry = self.entry.for_style(style);

        let mut pooled = PooledEntryWriter {
            inner: writer,
            prefix,
            forward_entry_metadata: self.forward_entry_metadata,
        };
        entry.write(&mut pooled);
    }

    fn descriptors<NS: NameStyle>(&self) -> Descriptors<'_> {
        let style = RuntimeStyle::for_ns::<NS>();
        let prefix = self.prefix::<NS>(style);
        let descriptors = self.entry.for_style(style).descriptors();

        if prefix.is_empty() {
            descriptors
        } else {
            descriptors.map_available(|descriptor| descriptor.with_prefix(prefix))
        }
    }

    fn prefix<NS: NameStyle>(&self, style: RuntimeStyle) -> &'static str {
        let namespace = namespace_prefix::<NS>();
        let handle = self.prefixes.for_style(style);
        match (namespace.is_empty(), handle.is_empty()) {
            (_, true) => namespace,
            (true, false) => handle,
            (false, false) => intern_prefix(format!("{namespace}{handle}")),
        }
    }
}

struct StyledEntries {
    identity: BoxEntry,
    pascal: BoxEntry,
    snake: BoxEntry,
    kebab: BoxEntry,
}

impl StyledEntries {
    fn for_style(&self, style: RuntimeStyle) -> &BoxEntry {
        match style {
            RuntimeStyle::Identity => &self.identity,
            RuntimeStyle::PascalCase => &self.pascal,
            RuntimeStyle::SnakeCase => &self.snake,
            RuntimeStyle::KebabCase => &self.kebab,
        }
    }
}

struct RuntimeInflectedEntry<M> {
    entry: Arc<M>,
    style: RuntimeStyle,
}

impl<M> RuntimeInflectedEntry<M> {
    fn new(entry: Arc<M>, style: RuntimeStyle) -> Self {
        Self { entry, style }
    }
}

impl<M> Entry for RuntimeInflectedEntry<M>
where
    M: InflectableEntry<Identity>
        + InflectableEntry<PascalCase>
        + InflectableEntry<SnakeCase>
        + InflectableEntry<KebabCase>,
{
    fn write<'a>(&'a self, writer: &mut impl EntryWriter<'a>) {
        match self.style {
            RuntimeStyle::Identity => InflectableEntry::<Identity>::write(&self.entry, writer),
            RuntimeStyle::PascalCase => InflectableEntry::<PascalCase>::write(&self.entry, writer),
            RuntimeStyle::SnakeCase => InflectableEntry::<SnakeCase>::write(&self.entry, writer),
            RuntimeStyle::KebabCase => InflectableEntry::<KebabCase>::write(&self.entry, writer),
        }
    }

    fn descriptors(&self) -> Descriptors<'_> {
        match self.style {
            RuntimeStyle::Identity => InflectableEntry::<Identity>::descriptors(&self.entry),
            RuntimeStyle::PascalCase => InflectableEntry::<PascalCase>::descriptors(&self.entry),
            RuntimeStyle::SnakeCase => InflectableEntry::<SnakeCase>::descriptors(&self.entry),
            RuntimeStyle::KebabCase => InflectableEntry::<KebabCase>::descriptors(&self.entry),
        }
    }
}

/// Suppresses child entry metadata unless explicitly enabled and prepends the
/// producer's prefix to each field name.
struct PooledEntryWriter<'a, W> {
    inner: &'a mut W,
    prefix: &'static str,
    forward_entry_metadata: bool,
}

impl<'a, W: EntryWriter<'a>> EntryWriter<'a> for PooledEntryWriter<'_, W> {
    fn timestamp(&mut self, timestamp: std::time::SystemTime) {
        if self.forward_entry_metadata {
            self.inner.timestamp(timestamp);
        }
    }

    fn value(&mut self, name: impl Into<Cow<'a, str>>, value: &(impl Value + ?Sized)) {
        let name = name.into();
        if self.prefix.is_empty() {
            self.inner.value(name, value);
            return;
        }

        let mut prefixed = String::with_capacity(self.prefix.len() + name.len());
        prefixed.push_str(self.prefix);
        prefixed.push_str(name.as_ref());
        self.inner.value(Cow::Owned(prefixed), value);
    }

    fn config(&mut self, config: &'a dyn EntryConfig) {
        if self.forward_entry_metadata {
            self.inner.config(config);
        }
    }
}

/// Capture the current metrics pool and propagate it while `future` is polled.
///
/// Capture happens synchronously when this function is called, before an
/// executor can detach the returned future. When a pool is captured, it is
/// installed for every poll using [`MetricsPoolHandle::scope`]. If no pool is
/// current at capture time, the input future is polled without adding a scope.
///
/// This wrapper is executor-independent, but it must be applied at a spawn site
/// controlled by the caller; it cannot affect tasks spawned internally by a
/// third-party library.
///
/// ```no_run
/// use metrique_util::{MetricsPool, propagate_current};
///
/// # async fn example() {
/// # let pool = MetricsPool::new();
/// pool.handle()
///     .scope(async {
///         tokio::spawn(propagate_current(async {
///             let pool = MetricsPool::current().expect("pool was propagated");
///             // Detached work can append through `pool` here.
///             # drop(pool);
///         }))
///         .await
///         .unwrap();
///     })
///     .await;
/// # }
/// ```
#[must_use = "futures do nothing unless polled"]
pub fn propagate_current<F: Future>(future: F) -> impl Future<Output = F::Output> {
    let pool = MetricsPool::current();
    async move {
        match pool {
            Some(pool) => pool.scope(future).await,
            None => future.await,
        }
    }
}

/// Run `future` with `pool` available through [`MetricsPool::current`].
pub fn with_metrics_pool<F>(pool: MetricsPoolHandle, future: F) -> MetricsPoolScope<F> {
    pool.scope(future)
}
